apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: localnet-ovs-br42
  namespace: challer-talos-oemc01
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "localnet-ovs-br42",
    "type": "ovn-k8s-cni-overlay",
    "topology": "localnet",
    "subnets": "10.42.0.0/24",
    "excludeSubnets": "10.42.0.0/25",
    "netAttachDefName": "challer-talos-oemc01/localnet-ovs-br42"
  }'
