apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br42-ens5-policy
spec:
  nodeSelector:
    cpu-feature.node.kubevirt.io/vmx: "true"
  desiredState:
    interfaces:
    - name: ovs-br42
      description: |-
        A dedicated OVS bridge with ens5 as a port
        allowing all VLANs and untagged traffic
      type: ovs-bridge
      ipv4:
        dhcp: false
        enabled: true
        address:
        - ip: 10.42.0.10
          prefix-length: 24
      state: up
      bridge:
        allow-extra-patch-ports: true
        options:
          stp: false
        port:
        - name: ens5
    ovn:
      bridge-mappings:
      - localnet: localnet-ovs-br42
        bridge: ovs-br42
        state: present
