apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br42-ens5-policy
spec:
  nodeSelector:
    cpu-feature.node.kubevirt.io/vmx: "true"
  desiredState:
    interfaces:
    - bridge:
        options:
          datapath: ""
          fail-mode: ""
          mcast-snooping-enable: false
          rstp: false
          stp:
            enabled: false
        port: []
      name: ovs-br42
      ovs-db:
        external_ids: {}
        other_config: {}
      state: absent
      type: ovs-bridge
    #ovn:
    #  bridge-mappings:
    #  - bridge: ovs-br42
    #    localnet: localnet-ovs-br42
    #    state: absent
