apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br42-ens5-policy 
spec:
  nodeSelector: 
    cpu-feature.node.kubevirt.io/vmx: "true"
  maxUnavailable: 2
  desiredState:
    interfaces:
      - name: br42
        description: Linux bridge with ens5 as a port 
        type: linux-bridge
        state: up
        ipv4:
          dhcp: true
          enabled: true
          auto-dns: false
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: ens5
    dns-resolver: 
      config:
        search:
        - example.com
        - example.org
        server:
        - 8.8.8.8
