apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: talos-cp01-data
  namespace: challer-talos-oemc01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-csi-immediate
